CONNECT TO SAMPLE; 

CREATE OR REPLACE FUNCTION SLEEP (SECOND INTEGER)
    RETURNS INTEGER
    SPECIFIC SLEEP_WITH_RETURN0
    LANGUAGE C
    PARAMETER STYLE SQL
    DETERMINISTIC
    FENCED
    NO SQL
    NO EXTERNAL ACTION
    EXTERNAL NAME 'sleep!sleeper'
;
 
GRANT EXECUTE ON FUNCTION SLEEP TO PUBLIC;

CONNECT RESET;
